/*
 * Digikam
 * RESTful Backend for Digikam
 *
 * The version of the OpenAPI document: 1.0
 * Contact: braun.h.michael@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.braun.digikam.backend.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;

/**
 * StatCreator
 */
@JsonPropertyOrder({
  StatCreator.JSON_PROPERTY_COUNT,
  StatCreator.JSON_PROPERTY_CAMERA,
  StatCreator.JSON_PROPERTY_CREATOR
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2025-03-10T18:21:26.080365595+01:00[Europe/Berlin]", comments = "Generator version: 7.7.0")
public class StatCreator   {
  public static final String JSON_PROPERTY_COUNT = "count";
  @JsonProperty(JSON_PROPERTY_COUNT)
  private Integer count;

  public static final String JSON_PROPERTY_CAMERA = "camera";
  @JsonProperty(JSON_PROPERTY_CAMERA)
  private String camera;

  public static final String JSON_PROPERTY_CREATOR = "creator";
  @JsonProperty(JSON_PROPERTY_CREATOR)
  private String creator;

  public StatCreator count(Integer count) {
    this.count = count;
    return this;
  }

  /**
   * Get count
   * @return count
   **/
  @JsonProperty(value = "count")
  @ApiModelProperty(required = true, value = "")
  @NotNull 
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public StatCreator camera(String camera) {
    this.camera = camera;
    return this;
  }

  /**
   * Get camera
   * @return camera
   **/
  @JsonProperty(value = "camera")
  @ApiModelProperty(required = true, value = "")
  @NotNull 
  public String getCamera() {
    return camera;
  }

  public void setCamera(String camera) {
    this.camera = camera;
  }

  public StatCreator creator(String creator) {
    this.creator = creator;
    return this;
  }

  /**
   * Get creator
   * @return creator
   **/
  @JsonProperty(value = "creator")
  @ApiModelProperty(required = true, value = "")
  @NotNull 
  public String getCreator() {
    return creator;
  }

  public void setCreator(String creator) {
    this.creator = creator;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatCreator statCreator = (StatCreator) o;
    return Objects.equals(this.count, statCreator.count) &&
        Objects.equals(this.camera, statCreator.camera) &&
        Objects.equals(this.creator, statCreator.creator);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, camera, creator);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatCreator {\n");
    
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    camera: ").append(toIndentedString(camera)).append("\n");
    sb.append("    creator: ").append(toIndentedString(creator)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

