/*
 * Digikam
 * RESTful Backend for Digikam
 *
 * The version of the OpenAPI document: 1.0
 * Contact: braun.h.michael@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.braun.digikam.backend.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;

/**
 * StatGlobal
 */
@JsonPropertyOrder({
  StatGlobal.JSON_PROPERTY_ORDER,
  StatGlobal.JSON_PROPERTY_NAME,
  StatGlobal.JSON_PROPERTY_COUNT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2025-03-10T18:21:26.080365595+01:00[Europe/Berlin]", comments = "Generator version: 7.7.0")
public class StatGlobal   {
  public static final String JSON_PROPERTY_ORDER = "order";
  @JsonProperty(JSON_PROPERTY_ORDER)
  private Integer order;

  public static final String JSON_PROPERTY_NAME = "name";
  @JsonProperty(JSON_PROPERTY_NAME)
  private String name;

  public static final String JSON_PROPERTY_COUNT = "count";
  @JsonProperty(JSON_PROPERTY_COUNT)
  private Integer count;

  public StatGlobal order(Integer order) {
    this.order = order;
    return this;
  }

  /**
   * Get order
   * @return order
   **/
  @JsonProperty(value = "order")
  @ApiModelProperty(required = true, value = "")
  @NotNull 
  public Integer getOrder() {
    return order;
  }

  public void setOrder(Integer order) {
    this.order = order;
  }

  public StatGlobal name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   **/
  @JsonProperty(value = "name")
  @ApiModelProperty(required = true, value = "")
  @NotNull 
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public StatGlobal count(Integer count) {
    this.count = count;
    return this;
  }

  /**
   * Get count
   * @return count
   **/
  @JsonProperty(value = "count")
  @ApiModelProperty(required = true, value = "")
  @NotNull 
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatGlobal statGlobal = (StatGlobal) o;
    return Objects.equals(this.order, statGlobal.order) &&
        Objects.equals(this.name, statGlobal.name) &&
        Objects.equals(this.count, statGlobal.count);
  }

  @Override
  public int hashCode() {
    return Objects.hash(order, name, count);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatGlobal {\n");
    
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

