/*
 * Digikam
 * RESTful Backend for Digikam
 *
 * The version of the OpenAPI document: 1.0
 * Contact: braun.h.michael@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.braun.digikam.backend.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * StatisticMonth
 */
@JsonPropertyOrder({
  StatisticMonth.JSON_PROPERTY_YEAR,
  StatisticMonth.JSON_PROPERTY_MONTH,
  StatisticMonth.JSON_PROPERTY_CNT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2023-12-27T20:04:01.965701513+01:00[Europe/Berlin]")
public class StatisticMonth   {
  public static final String JSON_PROPERTY_YEAR = "year";
  @JsonProperty(JSON_PROPERTY_YEAR)
  private Integer year;

  public static final String JSON_PROPERTY_MONTH = "month";
  @JsonProperty(JSON_PROPERTY_MONTH)
  private Integer month;

  public static final String JSON_PROPERTY_CNT = "cnt";
  @JsonProperty(JSON_PROPERTY_CNT)
  private Integer cnt;

  public StatisticMonth year(Integer year) {
    this.year = year;
    return this;
  }

  /**
   * Get year
   * @return year
   **/
  @JsonProperty(value = "year")
  @ApiModelProperty(required = true, value = "")
  @NotNull 
  public Integer getYear() {
    return year;
  }

  public void setYear(Integer year) {
    this.year = year;
  }

  public StatisticMonth month(Integer month) {
    this.month = month;
    return this;
  }

  /**
   * Get month
   * @return month
   **/
  @JsonProperty(value = "month")
  @ApiModelProperty(required = true, value = "")
  @NotNull 
  public Integer getMonth() {
    return month;
  }

  public void setMonth(Integer month) {
    this.month = month;
  }

  public StatisticMonth cnt(Integer cnt) {
    this.cnt = cnt;
    return this;
  }

  /**
   * Get cnt
   * @return cnt
   **/
  @JsonProperty(value = "cnt")
  @ApiModelProperty(required = true, value = "")
  @NotNull 
  public Integer getCnt() {
    return cnt;
  }

  public void setCnt(Integer cnt) {
    this.cnt = cnt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatisticMonth statisticMonth = (StatisticMonth) o;
    return Objects.equals(this.year, statisticMonth.year) &&
        Objects.equals(this.month, statisticMonth.month) &&
        Objects.equals(this.cnt, statisticMonth.cnt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(year, month, cnt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatisticMonth {\n");
    
    sb.append("    year: ").append(toIndentedString(year)).append("\n");
    sb.append("    month: ").append(toIndentedString(month)).append("\n");
    sb.append("    cnt: ").append(toIndentedString(cnt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

