/*
 * Digikam
 * RESTful Backend for Digikam
 *
 * The version of the OpenAPI document: 1.0
 * Contact: braun.h.michael@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.braun.digikam.backend.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

/**
 * Statistic
 */
@JsonPropertyOrder({
  Statistic.JSON_PROPERTY_GLOBAL,
  Statistic.JSON_PROPERTY_CREATORS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "2025-03-10T18:21:26.080365595+01:00[Europe/Berlin]", comments = "Generator version: 7.7.0")
public class Statistic   {
  public static final String JSON_PROPERTY_GLOBAL = "global";
  @JsonProperty(JSON_PROPERTY_GLOBAL)
  private List<@Valid StatGlobal> global = new ArrayList<>();

  public static final String JSON_PROPERTY_CREATORS = "creators";
  @JsonProperty(JSON_PROPERTY_CREATORS)
  private List<@Valid StatCreator> creators = new ArrayList<>();

  public Statistic global(List<@Valid StatGlobal> global) {
    this.global = global;
    return this;
  }

  public Statistic addGlobalItem(StatGlobal globalItem) {
    if (this.global == null) {
      this.global = new ArrayList<>();
    }
    this.global.add(globalItem);
    return this;
  }

  /**
   * Get global
   * @return global
   **/
  @JsonProperty(value = "global")
  @ApiModelProperty(required = true, value = "")
  @NotNull @Valid 
  public List<@Valid StatGlobal> getGlobal() {
    return global;
  }

  public void setGlobal(List<@Valid StatGlobal> global) {
    this.global = global;
  }

  public Statistic creators(List<@Valid StatCreator> creators) {
    this.creators = creators;
    return this;
  }

  public Statistic addCreatorsItem(StatCreator creatorsItem) {
    if (this.creators == null) {
      this.creators = new ArrayList<>();
    }
    this.creators.add(creatorsItem);
    return this;
  }

  /**
   * Get creators
   * @return creators
   **/
  @JsonProperty(value = "creators")
  @ApiModelProperty(required = true, value = "")
  @NotNull @Valid 
  public List<@Valid StatCreator> getCreators() {
    return creators;
  }

  public void setCreators(List<@Valid StatCreator> creators) {
    this.creators = creators;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Statistic statistic = (Statistic) o;
    return Objects.equals(this.global, statistic.global) &&
        Objects.equals(this.creators, statistic.creators);
  }

  @Override
  public int hashCode() {
    return Objects.hash(global, creators);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Statistic {\n");
    
    sb.append("    global: ").append(toIndentedString(global)).append("\n");
    sb.append("    creators: ").append(toIndentedString(creators)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

