/*
 * Digikam
 * RESTful Backend for Digikam
 *
 * The version of the OpenAPI document: 1.0
 * Contact: braun.h.michael@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.braun.digikam.client.api;

import org.braun.digikam.client.invoker.ApiException;
import org.braun.digikam.client.model.Creator;
import java.util.List;
import org.junit.jupiter.api.Test;

/**
 * API tests for CreatorApi
 */
public class CreatorApiTest {

    private final CreatorApi api = new CreatorApi();

    /**
     * Find Creator of an Image by Name
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findCreatorsByNameTest() throws ApiException {
        String name = "";
        List<Creator> response = api.findCreatorsByName(name);
        System.out.println(response.size());
        // TODO: test validations
    }
}
