/*
 * Digikam
 * RESTful Backend for Digikam
 *
 * The version of the OpenAPI document: 1.0
 * Contact: braun.h.michael@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.braun.digikam.client.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.StringJoiner;

/**
 * Image
 */
@JsonPropertyOrder({
  Image.JSON_PROPERTY_CREATOR,
  Image.JSON_PROPERTY_ORIENTATION,
  Image.JSON_PROPERTY_EXPOSURE_TIME,
  Image.JSON_PROPERTY_LATITUDE,
  Image.JSON_PROPERTY_FOCAL_LENGTH35,
  Image.JSON_PROPERTY_LENS,
  Image.JSON_PROPERTY_CREATION_DATE,
  Image.JSON_PROPERTY_APERTURE,
  Image.JSON_PROPERTY_WIDTH,
  Image.JSON_PROPERTY_MODEL,
  Image.JSON_PROPERTY_ID,
  Image.JSON_PROPERTY_MAKE,
  Image.JSON_PROPERTY_HEIGHT,
  Image.JSON_PROPERTY_FOCAL_LENGTH,
  Image.JSON_PROPERTY_LONGITUDE,
  Image.JSON_PROPERTY_ISO,
  Image.JSON_PROPERTY_RATING,
  Image.JSON_PROPERTY_KEYWORDS,
  Image.JSON_PROPERTY_TITLE,
  Image.JSON_PROPERTY_DESCRIPTION,
  Image.JSON_PROPERTY_RELATIVE_PATH,
  Image.JSON_PROPERTY_NAME
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-05-08T15:27:22.505089242+02:00[Europe/Berlin]")
public class Image {
  public static final String JSON_PROPERTY_CREATOR = "creator";
  private String creator;

  /**
   * Gets or Sets orientation
   */
  public enum OrientationEnum {
    PORTRAIT("portrait"),
    
    LANDSCAPE("landscape");

    private String value;

    OrientationEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OrientationEnum fromValue(String value) {
      for (OrientationEnum b : OrientationEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ORIENTATION = "orientation";
  private OrientationEnum orientation;

  public static final String JSON_PROPERTY_EXPOSURE_TIME = "exposureTime";
  private Double exposureTime;

  public static final String JSON_PROPERTY_LATITUDE = "latitude";
  private Double latitude;

  public static final String JSON_PROPERTY_FOCAL_LENGTH35 = "focalLength35";
  private Double focalLength35;

  public static final String JSON_PROPERTY_LENS = "lens";
  private String lens;

  public static final String JSON_PROPERTY_CREATION_DATE = "creationDate";
  private LocalDateTime creationDate;

  public static final String JSON_PROPERTY_APERTURE = "aperture";
  private Double aperture;

  public static final String JSON_PROPERTY_WIDTH = "width";
  private Integer width;

  public static final String JSON_PROPERTY_MODEL = "model";
  private String model;

  public static final String JSON_PROPERTY_ID = "id";
  private Integer id;

  public static final String JSON_PROPERTY_MAKE = "make";
  private String make;

  public static final String JSON_PROPERTY_HEIGHT = "height";
  private Integer height;

  public static final String JSON_PROPERTY_FOCAL_LENGTH = "focalLength";
  private Double focalLength;

  public static final String JSON_PROPERTY_LONGITUDE = "longitude";
  private Double longitude;

  public static final String JSON_PROPERTY_ISO = "iso";
  private Integer iso;

  public static final String JSON_PROPERTY_RATING = "rating";
  private Integer rating;

  public static final String JSON_PROPERTY_KEYWORDS = "keywords";
  private List<String> keywords;

  public static final String JSON_PROPERTY_TITLE = "title";
  private String title;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private String description;

  public static final String JSON_PROPERTY_RELATIVE_PATH = "relativePath";
  private String relativePath;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public Image() {
  }

  public Image creator(String creator) {
    
    this.creator = creator;
    return this;
  }

   /**
   * Name of the person, who has taken the picture
   * @return creator
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreator() {
    return creator;
  }


  @JsonProperty(JSON_PROPERTY_CREATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreator(String creator) {
    this.creator = creator;
  }


  public Image orientation(OrientationEnum orientation) {
    
    this.orientation = orientation;
    return this;
  }

   /**
   * Get orientation
   * @return orientation
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORIENTATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OrientationEnum getOrientation() {
    return orientation;
  }


  @JsonProperty(JSON_PROPERTY_ORIENTATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrientation(OrientationEnum orientation) {
    this.orientation = orientation;
  }


  public Image exposureTime(Double exposureTime) {
    
    this.exposureTime = exposureTime;
    return this;
  }

   /**
   * Get exposureTime
   * @return exposureTime
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPOSURE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getExposureTime() {
    return exposureTime;
  }


  @JsonProperty(JSON_PROPERTY_EXPOSURE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExposureTime(Double exposureTime) {
    this.exposureTime = exposureTime;
  }


  public Image latitude(Double latitude) {
    
    this.latitude = latitude;
    return this;
  }

   /**
   * Get latitude
   * @return latitude
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LATITUDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getLatitude() {
    return latitude;
  }


  @JsonProperty(JSON_PROPERTY_LATITUDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLatitude(Double latitude) {
    this.latitude = latitude;
  }


  public Image focalLength35(Double focalLength35) {
    
    this.focalLength35 = focalLength35;
    return this;
  }

   /**
   * Get focalLength35
   * @return focalLength35
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FOCAL_LENGTH35)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getFocalLength35() {
    return focalLength35;
  }


  @JsonProperty(JSON_PROPERTY_FOCAL_LENGTH35)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFocalLength35(Double focalLength35) {
    this.focalLength35 = focalLength35;
  }


  public Image lens(String lens) {
    
    this.lens = lens;
    return this;
  }

   /**
   * Get lens
   * @return lens
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LENS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLens() {
    return lens;
  }


  @JsonProperty(JSON_PROPERTY_LENS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLens(String lens) {
    this.lens = lens;
  }


  public Image creationDate(LocalDateTime creationDate) {
    
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Get creationDate
   * @return creationDate
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDateTime getCreationDate() {
    return creationDate;
  }


  @JsonProperty(JSON_PROPERTY_CREATION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreationDate(LocalDateTime creationDate) {
    this.creationDate = creationDate;
  }


  public Image aperture(Double aperture) {
    
    this.aperture = aperture;
    return this;
  }

   /**
   * Get aperture
   * @return aperture
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_APERTURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getAperture() {
    return aperture;
  }


  @JsonProperty(JSON_PROPERTY_APERTURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAperture(Double aperture) {
    this.aperture = aperture;
  }


  public Image width(Integer width) {
    
    this.width = width;
    return this;
  }

   /**
   * Get width
   * @return width
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WIDTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getWidth() {
    return width;
  }


  @JsonProperty(JSON_PROPERTY_WIDTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWidth(Integer width) {
    this.width = width;
  }


  public Image model(String model) {
    
    this.model = model;
    return this;
  }

   /**
   * Get model
   * @return model
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MODEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getModel() {
    return model;
  }


  @JsonProperty(JSON_PROPERTY_MODEL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setModel(String model) {
    this.model = model;
  }


  public Image id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * unique Id identifying an Image
   * @return id
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(Integer id) {
    this.id = id;
  }


  public Image make(String make) {
    
    this.make = make;
    return this;
  }

   /**
   * Get make
   * @return make
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MAKE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMake() {
    return make;
  }


  @JsonProperty(JSON_PROPERTY_MAKE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMake(String make) {
    this.make = make;
  }


  public Image height(Integer height) {
    
    this.height = height;
    return this;
  }

   /**
   * Get height
   * @return height
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getHeight() {
    return height;
  }


  @JsonProperty(JSON_PROPERTY_HEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeight(Integer height) {
    this.height = height;
  }


  public Image focalLength(Double focalLength) {
    
    this.focalLength = focalLength;
    return this;
  }

   /**
   * Get focalLength
   * @return focalLength
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FOCAL_LENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getFocalLength() {
    return focalLength;
  }


  @JsonProperty(JSON_PROPERTY_FOCAL_LENGTH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFocalLength(Double focalLength) {
    this.focalLength = focalLength;
  }


  public Image longitude(Double longitude) {
    
    this.longitude = longitude;
    return this;
  }

   /**
   * Get longitude
   * @return longitude
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LONGITUDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getLongitude() {
    return longitude;
  }


  @JsonProperty(JSON_PROPERTY_LONGITUDE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLongitude(Double longitude) {
    this.longitude = longitude;
  }


  public Image iso(Integer iso) {
    
    this.iso = iso;
    return this;
  }

   /**
   * Get iso
   * @return iso
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ISO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getIso() {
    return iso;
  }


  @JsonProperty(JSON_PROPERTY_ISO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIso(Integer iso) {
    this.iso = iso;
  }


  public Image rating(Integer rating) {
    
    this.rating = rating;
    return this;
  }

   /**
   * Get rating
   * @return rating
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RATING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRating() {
    return rating;
  }


  @JsonProperty(JSON_PROPERTY_RATING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRating(Integer rating) {
    this.rating = rating;
  }


  public Image keywords(List<String> keywords) {
    
    this.keywords = keywords;
    return this;
  }

  public Image addKeywordsItem(String keywordsItem) {
    if (this.keywords == null) {
      this.keywords = new ArrayList<>();
    }
    this.keywords.add(keywordsItem);
    return this;
  }

   /**
   * Get keywords
   * @return keywords
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KEYWORDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getKeywords() {
    return keywords;
  }


  @JsonProperty(JSON_PROPERTY_KEYWORDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKeywords(List<String> keywords) {
    this.keywords = keywords;
  }


  public Image title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTitle() {
    return title;
  }


  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitle(String title) {
    this.title = title;
  }


  public Image description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(String description) {
    this.description = description;
  }


  public Image relativePath(String relativePath) {
    
    this.relativePath = relativePath;
    return this;
  }

   /**
   * Get relativePath
   * @return relativePath
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RELATIVE_PATH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRelativePath() {
    return relativePath;
  }


  @JsonProperty(JSON_PROPERTY_RELATIVE_PATH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRelativePath(String relativePath) {
    this.relativePath = relativePath;
  }


  public Image name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Image image = (Image) o;
    return Objects.equals(this.creator, image.creator) &&
        Objects.equals(this.orientation, image.orientation) &&
        Objects.equals(this.exposureTime, image.exposureTime) &&
        Objects.equals(this.latitude, image.latitude) &&
        Objects.equals(this.focalLength35, image.focalLength35) &&
        Objects.equals(this.lens, image.lens) &&
        Objects.equals(this.creationDate, image.creationDate) &&
        Objects.equals(this.aperture, image.aperture) &&
        Objects.equals(this.width, image.width) &&
        Objects.equals(this.model, image.model) &&
        Objects.equals(this.id, image.id) &&
        Objects.equals(this.make, image.make) &&
        Objects.equals(this.height, image.height) &&
        Objects.equals(this.focalLength, image.focalLength) &&
        Objects.equals(this.longitude, image.longitude) &&
        Objects.equals(this.iso, image.iso) &&
        Objects.equals(this.rating, image.rating) &&
        Objects.equals(this.keywords, image.keywords) &&
        Objects.equals(this.title, image.title) &&
        Objects.equals(this.description, image.description) &&
        Objects.equals(this.relativePath, image.relativePath) &&
        Objects.equals(this.name, image.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creator, orientation, exposureTime, latitude, focalLength35, lens, creationDate, aperture, width, model, id, make, height, focalLength, longitude, iso, rating, keywords, title, description, relativePath, name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Image {\n");
    sb.append("    creator: ").append(toIndentedString(creator)).append("\n");
    sb.append("    orientation: ").append(toIndentedString(orientation)).append("\n");
    sb.append("    exposureTime: ").append(toIndentedString(exposureTime)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    focalLength35: ").append(toIndentedString(focalLength35)).append("\n");
    sb.append("    lens: ").append(toIndentedString(lens)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    aperture: ").append(toIndentedString(aperture)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    make: ").append(toIndentedString(make)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    focalLength: ").append(toIndentedString(focalLength)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("    iso: ").append(toIndentedString(iso)).append("\n");
    sb.append("    rating: ").append(toIndentedString(rating)).append("\n");
    sb.append("    keywords: ").append(toIndentedString(keywords)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    relativePath: ").append(toIndentedString(relativePath)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `creator` to the URL query string
    if (getCreator() != null) {
      try {
        joiner.add(String.format("%screator%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCreator()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `orientation` to the URL query string
    if (getOrientation() != null) {
      try {
        joiner.add(String.format("%sorientation%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getOrientation()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `exposureTime` to the URL query string
    if (getExposureTime() != null) {
      try {
        joiner.add(String.format("%sexposureTime%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getExposureTime()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `latitude` to the URL query string
    if (getLatitude() != null) {
      try {
        joiner.add(String.format("%slatitude%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getLatitude()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `focalLength35` to the URL query string
    if (getFocalLength35() != null) {
      try {
        joiner.add(String.format("%sfocalLength35%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getFocalLength35()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `lens` to the URL query string
    if (getLens() != null) {
      try {
        joiner.add(String.format("%slens%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getLens()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `creationDate` to the URL query string
    if (getCreationDate() != null) {
      try {
        joiner.add(String.format("%screationDate%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCreationDate()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `aperture` to the URL query string
    if (getAperture() != null) {
      try {
        joiner.add(String.format("%saperture%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAperture()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `width` to the URL query string
    if (getWidth() != null) {
      try {
        joiner.add(String.format("%swidth%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getWidth()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `model` to the URL query string
    if (getModel() != null) {
      try {
        joiner.add(String.format("%smodel%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getModel()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `id` to the URL query string
    if (getId() != null) {
      try {
        joiner.add(String.format("%sid%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `make` to the URL query string
    if (getMake() != null) {
      try {
        joiner.add(String.format("%smake%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMake()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `height` to the URL query string
    if (getHeight() != null) {
      try {
        joiner.add(String.format("%sheight%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getHeight()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `focalLength` to the URL query string
    if (getFocalLength() != null) {
      try {
        joiner.add(String.format("%sfocalLength%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getFocalLength()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `longitude` to the URL query string
    if (getLongitude() != null) {
      try {
        joiner.add(String.format("%slongitude%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getLongitude()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `iso` to the URL query string
    if (getIso() != null) {
      try {
        joiner.add(String.format("%siso%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getIso()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `rating` to the URL query string
    if (getRating() != null) {
      try {
        joiner.add(String.format("%srating%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getRating()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `keywords` to the URL query string
    if (getKeywords() != null) {
      for (int i = 0; i < getKeywords().size(); i++) {
        try {
          joiner.add(String.format("%skeywords%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
              URLEncoder.encode(String.valueOf(getKeywords().get(i)), "UTF-8").replaceAll("\\+", "%20")));
        } catch (UnsupportedEncodingException e) {
          // Should never happen, UTF-8 is always supported
          throw new RuntimeException(e);
        }
      }
    }

    // add `title` to the URL query string
    if (getTitle() != null) {
      try {
        joiner.add(String.format("%stitle%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTitle()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      try {
        joiner.add(String.format("%sdescription%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDescription()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `relativePath` to the URL query string
    if (getRelativePath() != null) {
      try {
        joiner.add(String.format("%srelativePath%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getRelativePath()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `name` to the URL query string
    if (getName() != null) {
      try {
        joiner.add(String.format("%sname%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

