/*
 * Digikam
 * RESTful Backend for Digikam
 *
 * The version of the OpenAPI document: 1.0
 * Contact: braun.h.michael@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.braun.digikam.client.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for Creator
 */
public class CreatorTest {
    private final Creator model = new Creator();

    /**
     * Model tests for Creator
     */
    @Test
    public void testCreator() {
        // TODO: test Creator
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
