/*
 * Digikam
 * RESTful Backend for Digikam
 *
 * The version of the OpenAPI document: 1.0
 * Contact: braun.h.michael@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.braun.digikam.client.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for ImagesInner
 */
public class ImagesInnerTest {
    private final ImagesInner model = new ImagesInner();

    /**
     * Model tests for ImagesInner
     */
    @Test
    public void testImagesInner() {
        // TODO: test ImagesInner
    }

    /**
     * Test the property 'imageId'
     */
    @Test
    public void imageIdTest() {
        // TODO: test imageId
    }

    /**
     * Test the property 'creationDate'
     */
    @Test
    public void creationDateTest() {
        // TODO: test creationDate
    }

}
