/*
 * Digikam
 * RESTful Backend for Digikam
 *
 * The version of the OpenAPI document: 1.0
 * Contact: braun.h.michael@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.braun.digikam.client.model;

import org.junit.jupiter.api.Test;


/**
 * Model tests for Keyword
 */
public class KeywordTest {
    private final Keyword model = new Keyword();

    /**
     * Model tests for Keyword
     */
    @Test
    public void testKeyword() {
        // TODO: test Keyword
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
